version: "3.8"

services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: rinha
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1.8GB"

  api01:
    build: .
    environment:
      ENABLE_DEBUG: false
      PORT: 80
      POSTGRES_DB: rinha
      POSTGRES_HOST: db
      POSTGRES_PASS: 123
      POSTGRES_PORT: 5432
      POSTGRES_USER: rinha
    hostname: rinha-api01
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "80"
      - "6060"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.35GB"

  api02:
    build: .
    environment:
      ENABLE_DEBUG: false
      PORT: 80
      POSTGRES_DB: rinha
      POSTGRES_HOST: db
      POSTGRES_PASS: 123
      POSTGRES_PORT: 5432
      POSTGRES_USER: rinha
    hostname: rinha-api02
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "80"
      - "6060"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.35GB"

  nginx:
    image: nginx:latest
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "0.5GB"

networks:
  default:
    driver: bridge
    name: rinha
